Permissions: true
VaultPermissions: true
AllowBlockPvP: true
Announcement: true
InformOnPartnerJoin: true
DelayMessageForJoiningPlayer: 0
Language: en
LanguageUpdateMode: Overwrite
PriestCMD: priest
UseUUIDs: true
UUID_Type: auto
AllowSelfMarry: false
AllowSelfDivorce: auto
Surname: false
AllowSurnameColors: false
AllowedSurnameCharacters: A-Za-z
AllowGiftsInCreative: false
UseMinepacks: false
UseBungeeCord: true
Chat:
  ToggleCommand: chattoggle
  PrivateFormat: '<heart> %1$s&r => %2$s: %3$s'
Economy:
  Enable: false
  Divorce: 100.0
  Marry: 100.0
  Tp: 25.0
  HomeTp: 25.0
  SetHome: 100.0
  Gift: 10.0
HealthRegain:
  Enable: true
  Amount: 2
BonusXp:
  Enable: true
  Multiplier: 2
Prefix:
  Enable: false
  String: <heart><partnername><heart>
  OnLineBeginning: true
Suffix:
  Enable: false
  String: ' (<heart><partnername><heart>)'
Database:
  Type: MySQL
  UpdatePlayer: true
  MySQL:
    Host: 198.245.51.96:3306
    Database: db_47152
    Properties: []
    User: db_47152
    Password: e87189c6b6
    MaxConnections: 2
  Tables:
    User: marry_players
    Home: marry_home
    Priests: marry_priests
    Partner: marry_partners
Confirmation:
  Enable: true
  AutoDialog: true
  BothPlayersOnDivorce: true
Kiss:
  Enable: true
  Interaction: true
  WaitTime: 10
  HearthCount: 50
  CompatibilityMode: false
Misc:
  AutoUpdate: true
  DisableV2Info: false
Range:
  Marry: 25.0
  Divorce: 25.0
  Kiss: 2.0
  KissInteract: 2.0
  HearthVisible: 128.0
  Heal: 2.0
  BonusXP: 10.0
  Gift: 0
  Backpack: 5
Teleport:
  Delay: false
  DelayTime: 3
  CheckSafety: true
  BlacklistedWorlds: []
RequireBothNamesOnPriestDivorce: false
Version: 28
