#######################################################################################
# +---------------------------------------------------------------------------------+ #
# |    ___ ___ __  __ ___ _    ___      ___ _    _____   ___ _____ ___  ___  ___    | #
# |   / __|_ _|  \/  | _ \ |  | __|    | __| |  | __\ \ / /_\_   _/ _ \| _ \/ __|   | #
# |   \__ \| || |\/| |  _/ |__| _|     | _|| |__| _| \ V / _ \| || (_) |   /\__ \   | #
# |   |___/___|_|  |_|_| |____|___|    |___|____|___| \_/_/ \_\_| \___/|_|_\|___/   | #
# |                                                                                 | #
# | By: Benz56                                                                      | #
# +---------------------------------------------------------------------------------+ #
#######################################################################################


# Update checker.
# If enabled you'll receive a message in console
# and as OP in chat when joining when a new update is available.
updateChecker: true

# Elevator Combinations:
# Add/Change as many combinations as you want. First Material is the block at your feet.
# Syntax: 'Material:Data, Material:Data' and 'Material:Data'.
# Use 'any' for any block. Only works for the bottom block. E.g. 'Quartz_Block, any'.
# You can also leave the second block empty for the same effect. E.g. 'Quartz_Block'.
# You can ignore data values by using a * as the Data value. (Not on 1.13!)
combinations:
 - 'Quartz_Block, Redstone_block'
 - 'Step:7, Iron_Block'
 - 'Carpet:14, Wool:11'
 - 'Stone:1, dirt:1'

# Enable/Disable worlds:
# Add worlds(Case-sensitive) to exclusively enable those e.g:
#
# enabledworlds:
#    - world
#    - world_nether
#
# The above example will enable Elevators ONLY in those worlds.
# Leave blank to enable all worlds.
enabledworlds:
  - world

# Max Elevator distance:
# Set to 255 or higher to ignore completely.
maxDistance: 40

# Replace blocks at destination Elevator:
# true will replace blocks at the destination when creating a set of Elevators.
createReplace: true

# Elevator sound:
# View supported sound enums here; https://jd.bukkit.org/org/bukkit/Sound.html
# And here; https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# Both 1.8 and 1.8+ Sounds enums are supported.
# Pitch: 0.5 to 2.0
# Volume: 0 to 1.0 (Larger values increases the distance from where it can be heard)
# World: Specifies whether the sound is played only to the elevated player or everyone in range.
elevatorSound:
 up:
  enabled: true
  sound: "ORB_PICKUP"
  pitch: 0.5
  world: false
 down:
  enabled: true
  sound: "ORB_PICKUP"
  pitch: 1
  world: false

# ActionBar: (Unsupported in 1.7)
actionBarEnabled: false
# Messages:
floorUp: '&e&lYou have been taken one floor &a&lUP'
floorDown: '&e&lYou have been taken one floor &c&lDOWN'

# TitleBar: (Unsupported in 1.7)
titleBarEnabled: true
# Messages:
floorUpTitle: '&a&lUP'
floorUpSubTitle: ''
floorDownTitle: '&c&lDOWN'
floorDownSubTitle: ''
# Settings:
titleBarFadeIn: 5
titleBarStay: 10
titleBarFadeOut: 5

# BossBar (Unsupported in 1.7 & 1.8)
bossBarEnabled: true
# Color: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
bossBarColor: WHITE
# Style: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
bossBarStyle: SOLID
# Message. Placeholders: %floor% == current floor & %totalFloors% == total floors.
bossBarMessage: '&eFloor %floor% of %totalFloors%'

# Arrow Particles:
arrow_enabled: true
# Enable/disable arrow on current and/or destination floor.
arrow_currentFloor: true
arrow_destinationFloor: true
# Every Minecraft color is Valid (names(e.g. red) and color codes (e.g &c):
# colors: http://imgur.com/a/v3TzU (Use 'random' for a random color)
arrow_color_up: 'green'
arrow_color_down: 'red'
# arrow size: (blocks in height)
arrow_size: 2.0

# Items that Elevators will ignore checking for.
# These items can be placed in the destination space.
# Remove/add any item you want. Use valid Material names and IDs.
# Ignore everything with: ignoreList: 'all'
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
ignoreList: 'air, torch, lever, stone_button, redstone_torch_on, redstone_torch_off, vine, wood_button, banner, sign, sign_post, wall_sign'

# Elevator delay:
# Set the delay of the elevators. The delay is in ticks (20 ticks == 1 second)
# If the player leaves the elevator before the time has passed they are not elevated.
delay: 0
# An actionbar countdown message sent to the player with the delay.
elevatorDelayMessage: '&a&lElevation in %seconds% seconds!'
# The message sent if the elevation is canceled by moving outside of the elevator.
elevatorCanceledMessage: '&c&lElevation canceled!'

# Set a delay before a player can use an elevator again.
# The delay is in ticks (20 ticks == 1 second)
elevatorCooldown: 0
# The cooldown message sent to the player if they try to use an elevator while in cooldown mode. Leave it blank to disable it.
# The %cooldown% placeholder is the time in seconds until they can use an elevator again.
elevatorCooldownMessage: '&cPlease wait %cooldown% seconds before using an elevator again!'

# Include an extra floor that is not an elevator above and/or below the elevator column.
lazyCheck:
 top: false
 bottom: false