Main:
  Only Show Players Kits They Have Permission To Use: false
  Allow Players To Receive Kits For Free If They Have Permission: true
  Dont Preview Commands In Kits: false
  Hologram Layout:
  - '{TITLE}'
  - '{LEFT-CLICK}'
  - '{RIGHT-CLICK}'
  Sounds Enabled: true
  Sound Played While Clicking In Inventories: ENTITY_ENDERMEN_TELEPORT
  Prevent The Redeeming of a Kit When Inventory Is Full: true
  Display Chance In Preview: true
  Currency Symbol: $
  Block Help Page For Non Admins: false
Interfaces:
  Exit Icon: WOOD_DOOR
  Buy Icon: EMERALD
  Glass Type 1: 7
  Glass Type 2: 11
  Glass Type 3: 3
  Replace Glass Type 1 With Rainbow Glass: false
  Do Not Use Glass Borders: false
System:
  Download Needed Data Files: true
  Language Mode: en_US
  Debugger Enabled: false
data:
  particlesettings:
    ammount: 25
    type: WITCH_MAGIC
