#List of all the enchantments: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
Settings:
  Prefix: '&eCrates &8» '
  InventoryName: ' &4&l&m----&8&l&m[--&r   &c&nCrates&r   &8&l&m--]&r&4&l&m----'
  InventorySize: 27
  KnockBack: true
  Update-Checker: true
  Show-Preview: true #Toggle this on and off if you want to show the preview for the crates when left clicked.
  Physical-Accepts-Virtual-Keys: true #If physical crates can accept virtual keys.
  Virtual-Accepts-Physical-Keys: true #If virtual crates can accept physical keys.
  QuadCrate:
    Timer: 300
  DisabledWorlds:
    - 'world_nether'
  Preview:
    Buttons:
      Menu:
        Item: 'COMPASS'
        Name: '&8◆ &b&nMenu&r &8◆'
        Lore:
          - '&7Return to the menu.'
      Next:
        Item: 'ARROW'
        Name: '&8◆ &e&nNext&r &8◆'
        Lore:
          - '&7Page: &c%page%'
      Back:
        Item: 'ARROW'
        Name: '&8◆ &6&nBack&r &8◆'
        Lore:
          - '&7Page: &c%page%'
  Filler: #This allows you to quickly fill the GUI with one item.
    Toggle: false #If it fills the GUI with an item.
    Item: '160:15' #The item you wish to use.
    Name: ' ' #The name of the item.
    Lore: {} #The lore of the item.
  GUI-Customizer: #Place extra items in the GUI. If you wish to not use this, remove all items and set it to GUI-Customizer: {}
    - 'Slot:1, Item:160:15, Name: '
    - 'Slot:2, Item:160:1, Name: '
    - 'Slot:3, Item:160:15, Name: '
    - 'Slot:4, Item:160:4, Name: '
    - 'Slot:5, Item:160:15, Name: '
    - 'Slot:6, Item:160:6, Name: '
    - 'Slot:7, Item:160:15, Name: '
    - 'Slot:8, Item:160:14, Name: '
    - 'Slot:9, Item:160:15, Name: '
    - 'Slot:10, Item:160:15, Name: '
    - 'Slot:12, Item:160:15, Name: '
    - 'Slot:14, Item:160:15, Name: '
    - 'Slot:16, Item:160:15, Name: '
    - 'Slot:18, Item:160:15, Name: '
    - 'Slot:19, Item:160:15, Name: '
    - 'Slot:20, Item:160:1, Name: '
    - 'Slot:21, Item:160:15, Name: '
    - 'Slot:22, Item:160:4, Name: '
    - 'Slot:23, Item:160:15, Name: '
    - 'Slot:24, Item:160:6, Name: '
    - 'Slot:25, Item:160:15, Name: '
    - 'Slot:26, Item:160:14, Name: '
    - 'Slot:27, Item:160:15, Name: '