# You can create generators as much as you want.
# Important: All generators should be named "generator1", "generator2", etc. 
# You can define the spawnrates of any block in the blocks-section.
# The spawnrates are in percent, for example 57.3 are 57,3%.
# All values together should be 100%. If all values together are higher or lower as 100, the plugin would'nt work correctly.
# The permissions are custom, so you can make a generator for VIPS, and give them the permission "oregen.vip".
# Are you finish with configuring? Just type /customoregen to reload the plugin!

# Note: If the Island's owner is offline, the cobblestone generator would be choose the first Generator-Config.

generators:
#  generator1:
#    # default generator
#    # name of the generator (does not need to be set, just for placeholders)
#    label: "beginner"
#    blocks:
#    # Please use Bukkit-Blocknames. List: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#    - STONE:50.0
#    - SANDSTONE:40.0
#    - IRON_ORE:10.0
#    permission: ''
#    # You can also define from what level the generator should be activated. Example: Leave all permissions empty and
#    # only work with the island Level. The plugin would only consider the islandLevel then.
#    unlock_islandLevel: 0
#  generator2:
#    # vip generator, VIPS need generators.vip permission
#    label: "VIP"
#    blocks:
#    - IRON_ORE:90.0
#    - STONE:5.0
#    - SANDSTONE:5.0
#    permission: 'oregen.vip'
#    unlock_islandLevel: 0
  tier1:
    label: "Tier I"
    blocks:
    - STONE:87.5
    - COAL_ORE:10.0
    - COAL_BLOCK:2.5
    permission: 'oregenerators.tier1'
    unlock_islandLevel: 0
  tier2:
    label: "Tier II"
    blocks:
    - STONE:70.0
    - COAL_ORE:12.5
    - COAL_BLOCK:5.0
    - IRON_ORE:10.0
    - IRON_BLOCK:2.5
    permission: 'oregenerators.tier2'
    unlock_islandLevel: 0
  tier3:
    label: "Tier III"
    blocks:
    - STONE:60.0
    - COAL_ORE:12.5
    - COAL_BLOCK:5.0
    - IRON_ORE:10.0
    - IRON_BLOCK:2.5
    - GOLD_ORE:8.5
    - GOLD_BLOCK:1.5
    permission: 'oregenerators.tier3'
    unlock_islandLevel: 0
  tier4:
    label: "Tier IV"
    blocks:
    - STONE:50.0
    - COAL_ORE:14.5
    - COAL_BLOCK:5.0
    - IRON_ORE:11.0
    - IRON_BLOCK:2.5
    - GOLD_ORE:9.5
    - GOLD_BLOCK:1.5
    - DIAMOND_ORE:5.0
    - DIAMOND_BLOCK:1.0
    permission: 'oregenerators.tier4'
    unlock_islandLevel: 0
  tier5:
    label: "Tier V"
    blocks:
    - STONE:40.0
    - COAL_ORE:16.5
    - COAL_BLOCK:5.0
    - IRON_ORE:13.0
    - IRON_BLOCK:2.5
    - GOLD_ORE:11.0
    - GOLD_BLOCK:1.5
    - DIAMOND_ORE:5.5
    - DIAMOND_BLOCK:1.0
    - EMERALD_ORE:3.5
    - EMERALD_BLOCK:0.5
    permission: 'oregenerators.tier5'
    unlock_islandLevel: 0
# Here you can define worlds where the generator should not work
disabled-worlds:
- "world_nether"
